apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nouranhamdy1998/aws-cli
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "50Mi"
            cpu: "200m"
          limits:
            memory: "50Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: roaming-aws-config-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: roaming-aws-config-credentials
              key: aws_secret_access_key
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: roaming-aws-config-credentials
              key: region
        









      #   volumeMounts:
      #   - name: aws-cred
      #     mountPath: "/root/.aws/"
      #     readOnly: true
      # volumes:
      # - name: aws-cred
      #   secret:
      #     secretName: aws-cred
      #     items:
      #     - key: aws_access_key_id
      #       path: credentials
      #     - key: aws_secret_access_key
      #       path: credentials
      