apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        resources:
          requests:
            memory: "50Mi"
            cpu: "200m"
          limits:
            memory: "50Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env:
        - name: ENV
          valueFrom:
            configMapKeyRef:
              name: config
              key: env
      - name: fluentbit
        image: fluent/fluent-bit:1.8.15
        resources:
          requests:
            memory: "150Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "50m"
              